name: clickhouse-poc

services:
  broker:
    image: apache/kafka-native:latest
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # One socket for containers (INTERNAL), one for the host (EXTERNAL)
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      # Map listener names to protocol
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Inter-broker traffic should use the INTERNAL listener
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "18123:8123"   # HTTP interface
      - "19000:9000"   # Native TCP interface
      - "9009:9009"   # gRPC interface (optional, can be removed)
      - "9363:9363"   #metrics
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_PASSWORD: changeme
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      # Increase the number of simultaneously open files a bit
      CLICKHOUSE_ULIMIT_NOFILE: 262144
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.d/clickhouse-config.xml
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    depends_on:
      - broker
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host localhost --query 'SELECT 1'" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  clickhouse-data:
    driver: local
  clickhouse-logs:
    driver: local